name = "quote-crm-system"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-27"

[[d1_databases]]
binding = "DB"
database_name = "quote-crm-system-db"
database_id = "47d5d2ca-d3fb-4f8d-ac99-fc4048941cee"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "quote-crm-system-images"
